apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobb-poc-frontend-useracceptance
  namespace: openshift-gitops
spec:
  project: useracceptance
  source:
    repoURL: 'https://github.com/MichaelMarkieta/mobb-poc-ops'
    path: apps/mobb-poc-frontend/overlays/useracceptance
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: useracceptance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
  revisionHistoryLimit: 5