namespace: development
resources:
  - ../../base
patchesStrategicMerge:
  - route.yaml
images:
  - name: mobb-poc-frontend
    newName: image-registry.openshift-image-registry.svc.cluster.local:5000/development/mobb-poc-frontend
    newTag: a88e78a23edea9bdfb87164581618c33ae034b6b
