namespace: development
resources:
  - ../../base
patchesStrategicMerge:
  - route.yaml
images:
  - name: mobb-poc-frontend
    newName: image-registry.openshift-image-registry.svc.cluster.local:5000/development/mobb-poc-frontend
    newTag: cc3287fe019b57ecb0742c2cbaf014518eea25c4
